POST http://localhost:9888/api/v1/wallet
Content-Type: application/json

{
    "name": "Arnaldo",
    "balance": "8000"
}

###

POST http://localhost:9888/api/v1/wallet
Content-Type: application/json

{
    "name": "Bernaldo",
    "balance": "5000"
}