services: 
  postgres: 
    image: postgres
    volumes: 
     - ./db/01-initdb.sql:/docker-entrypoint-initdb.d/01-initdb.sql
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"

volumes:
  pgdata: